# Generated by Django 4.1.2 on 2022-11-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beta_testing',
            field=models.BooleanField(default=False, verbose_name='Хочу участвовать в бета-тестировании'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_development_interview',
            field=models.BooleanField(default=False, verbose_name='Готов поговорить об опыте использования похожих сервисов (доставка, кулинария, фудшеринг)'),
        ),
    ]
