# Generated by Django 4.0.5 on 2022-06-27 06:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('amount', models.FloatField(null=True, verbose_name='Количество продукта')),
                ('amount_unit', models.CharField(choices=[('мг', 'миллиграммы'), ('г', 'граммы'), ('кг', 'килограммы'), ('мл', 'миллилитры'), ('л', 'литры')], max_length=2, null=True, verbose_name='Единица измерения количества продукта')),
                ('production_date', models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime.now)], verbose_name='Дата изготовления')),
                ('purchase_date', models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime.now)], verbose_name='Дата покупки')),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='book.productcard')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
