# Generated by Django 4.0.5 on 2022-06-26 15:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2022, 6, 26, 20, 30, 26, 214765))], verbose_name='Дата изготовления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2022, 6, 26, 20, 30, 26, 214765))], verbose_name='Дата покупки'),
        ),
    ]
