# Generated by Django 4.0.5 on 2022-06-26 16:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_production_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2022, 6, 26, 21, 4, 45, 352050))], verbose_name='Дата изготовления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2022, 6, 26, 21, 4, 45, 352050))], verbose_name='Дата покупки'),
        ),
    ]
