# Generated by Django 4.0.5 on 2022-07-06 08:29

import core.middleware
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount_unit',
            field=models.CharField(blank=True, choices=[('мг', 'миллиграммы'), ('г', 'граммы'), ('кг', 'килограммы'), ('мл', 'миллилитры'), ('л', 'литры')], default=('г', 'граммы'), max_length=2, null=True, verbose_name='Единица измерения количества продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=core.middleware.get_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
