# Generated by Django 4.0.5 on 2022-06-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='title',
        ),
        migrations.AddField(
            model_name='productcard',
            name='designation',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='book.productcategory', verbose_name='Категория продуктов'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
