# Generated by Django 4.0.5 on 2022-06-25 13:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_productcard_is_published_recipe_is_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productcard',
            managers=[
                ('cards', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productsubcategory',
            managers=[
                ('subcategories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='productcard',
            name='shelf_life',
            field=models.DurationField(null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='shelf_life_after_opening',
            field=models.DurationField(null=True, verbose_name='Срок годности'),
        ),
    ]
