# Generated by Django 4.0.5 on 2022-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_productcard_storage_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='max_storage_temperature_unit',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='min_storage_temperature_unit',
        ),
        migrations.AddField(
            model_name='productcard',
            name='storage_temperature_unit',
            field=models.CharField(blank=True, choices=[('℃', 'градус Цельсия'), ('℉', 'градус Фаренгейта'), ('K', 'Кельвин')], max_length=3, null=True, verbose_name='Единица измерения температуры хранения'),
        ),
    ]
