# Generated by Django 4.0.5 on 2022-07-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_productcard_max_storage_temperature_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images', verbose_name='Изображение продукта'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='storage_temperature_unit',
            field=models.CharField(blank=True, choices=[('℃', 'градус Цельсия'), ('℉', 'градус Фаренгейта'), ('K', 'Кельвин')], default=('℃', 'градус Цельсия'), max_length=3, null=True, verbose_name='Единица измерения температуры хранения'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images', verbose_name='Изображение блюда'),
        ),
        migrations.AlterField(
            model_name='recipephoto',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/gallery'),
        ),
    ]
