# Generated by Django 4.0.5 on 2022-07-05 01:38

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_productcard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, validators=[core.validators.BiggerThanValidator(0)], verbose_name='Углеводы (в граммах)'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='energy_value',
            field=models.FloatField(blank=True, help_text='Энергетическая ценность на 100 грамм продукта', null=True, validators=[core.validators.BiggerThanValidator(0)], verbose_name='Энергетическая ценность'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='energy_value_unit',
            field=models.CharField(choices=[('ккал', 'ккал'), ('кДж', 'кДж')], default=('ккал', 'ккал'), max_length=4, verbose_name='Единица измерения энергетической ценности'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='fats',
            field=models.FloatField(blank=True, null=True, validators=[core.validators.BiggerThanValidator(0)], verbose_name='Жиры (в граммах)'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='proteins',
            field=models.FloatField(blank=True, null=True, validators=[core.validators.BiggerThanValidator(0)], verbose_name='Белки (в граммах)'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='storage_temperature_unit',
            field=models.CharField(choices=[('℃', '℃'), ('℉', '℉'), ('K', 'K')], default=('℃', '℃'), max_length=3, verbose_name='Единица измерения температуры хранения'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='book.productsubcategory', verbose_name='Подкатегория продуктов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='energy_value',
            field=models.FloatField(blank=True, null=True, validators=[core.validators.BiggerThanValidator(0)], verbose_name='Энергетическая ценность'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='energy_value_unit',
            field=models.CharField(blank=True, choices=[('ккал', 'ккал'), ('кДж', 'кДж')], max_length=4, null=True, verbose_name='Единица измерения энергетической ценности'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='people_count',
            field=models.IntegerField(default=1, help_text='Количество человек, на которое рассчитано блюдо', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во человек'),
        ),
    ]
