# Generated by Django 4.0.5 on 2022-07-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_productcard_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='gallery',
            field=models.ManyToManyField(related_name='product_cards', to='book.productphoto', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_cards', to='book.productsubcategory', verbose_name='Подкатегория продуктов'),
        ),
    ]
